name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        service: [
          "services/node/api-node",
          "services/go/api-golang",
          "services/react/client-react"
          ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6 # v4.4.0
        with:
          node-version-file: ${{ matrix.service }}/package.json
          cache: "npm"
          cache-dependency-path: ${{ matrix.service }}/package-lock.json
        if: ${{ startsWith(matrix.service, 'services/node') || startsWith(matrix.service, 'services/react') }}
      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: services/go/api-golang/go.mod
          cache-dependency-path: services/go/api-golang/go.sum
        if: ${{ startsWith(matrix.service, 'services/go') }}
      - name: Install task
        uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 # v4.0.1
        with:
          uri: https://github.com/go-task/task/releases/download/v3.44.1/task_linux_amd64.tar.gz
          sha256: 72991d4f041e18d925d073e54bc7d264a6d361fb
          version: v3.44.1
          name: task
      - name: Install app deps
        working-directory: ${{ matrix.service }}
        run: |
          task install-ci
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: |
          task test
